USER_ID = '1099'
TEAM_ID = '1319'
USER_AGENT = "XY"
TEAM_NAME = 'KarabakhIsAzerbaijan'
API_KEY = '667b3027a12fdfef488b'
API_URL = 'https://www.notexponential.com'
API_INDEX = API_URL + '/aip2pgaming/api/index.php'
GAMES = ['Test', 'Test Continue', 'Opponent New', 'Opponent Join']
GAME = GAMES[2]
MARGIN = 20